[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/facebook-posts"
  to = "/.netlify/functions/facebook-posts"
  status = 200

[[redirects]]
  from = "/api/instagram-posts"
  to = "/.netlify/functions/instagram-posts"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200